name: Release

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  publish:
    if: github.event_name == 'push' && github.ref == 'refs/heads/main'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: pnpm/action-setup@v2
        with:
          version: 9.9.0
      - uses: actions/setup-node@v2
        with:
          node-version: '20.6'
          registry-url: 'https://registry.npmjs.org'
      - run: pnpm install
      - run: pnpm lint
      - run: pnpm build
      - run: pnpm publish --access=public
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}